//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int IDKorisnika { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string BrojTelefona { get; set; }
        public string Username { get; set; }
        public string Sifra { get; set; }
        public string Adresa { get; set; }
        public bool Admin { get; set; }
    
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
