//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokacija
    {
        public Lokacija()
        {
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int IDLokacija { get; set; }
        public string Naziv { get; set; }
        public string AdresaPocetka { get; set; }
        public string AdresaVracanja { get; set; }
    
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
