//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrijeme
    {
        public Vrijeme()
        {
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int IDVrijeme { get; set; }
        public System.DateTime VrijemePocetka { get; set; }
        public System.DateTime VrijemeZavrsetka { get; set; }
        public System.DateTime VrijemeVracanja { get; set; }
    
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
